export const colors = {
  background: {
    base: "rgb(3, 3, 3)",
    surface: "rgb(17, 17, 17)",
    raised: "rgb(26, 26, 26)",
    elevated: "rgb(31, 31, 31)",
    highlight: "rgb(38, 38, 38)",
    inverse: "rgb(246, 246, 246)",
  },
  text: {
    primary: "rgb(246, 246, 246)",
    secondary: "rgb(149, 149, 149)",
    muted: "rgb(107, 107, 107)",
    inverse: "rgb(10, 10, 10)",
  },
  main: {
    border: "rgb(46, 46, 46)",
    brand: "rgb(255, 188, 44)",
    accentHot: "rgb(255, 119, 0)",
    accentWarm: "rgb(255, 153, 44)",
    accentLight: "rgb(255, 221, 147)",
  },
} as const;

export const typography = {
  displayXl: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "54px",
    lineHeight: "1.1em",
    letterSpacing: "-0.03em",
  },
  displayL: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "44px",
    lineHeight: "1.1em",
    letterSpacing: "-0.03em",
  },
  headingXl: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "40px",
    lineHeight: "1.2em",
    letterSpacing: "-0.03em",
  },
  headingL: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "28px",
    lineHeight: "1.2em",
    letterSpacing: "-0.03em",
  },
  headingM: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "24px",
    lineHeight: "1.3em",
    letterSpacing: "-0.03em",
  },
  textL: {
    fontFamily: "Geist",
    fontWeight: 500,
    fontSize: "20px",
    lineHeight: "1.4em",
    letterSpacing: "-0.03em",
  },
  textM: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
  },
  bodyMRegular: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
  },
  bodyMMedium: {
    fontFamily: "Geist",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
  },
  bodySRegular: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
  },
  bodySMedium: {
    fontFamily: "Geist",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
  },
  bodyXs: {
    fontFamily: "Geist",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
  },
  label: {
    fontFamily: "Geist",
    fontWeight: 500,
    fontSize: "11px",
    lineHeight: "1.5em",
    letterSpacing: "-0.03em",
    textTransform: "uppercase" as const,
  },
} as const;
